# Generated by Django 3.2 on 2021-04-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Counterparty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('EM', 'E-MAIL'), ('PH', 'PHONE'), ('ST', 'SITE'), ('PR', 'PORTAL'), ('AD', 'ADDRESS')], max_length=2, verbose_name='Тип')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Контактное лицо')),
                ('value', models.CharField(max_length=255, verbose_name='Контакт')),
                ('additional_info', models.CharField(default=None, max_length=255, verbose_name='Дополнительные данные')),
                ('partner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Counterparty.partner')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contacts',
            },
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['contact_type'], name='contacts_contact_8d5bcc_idx'),
        ),
    ]
