# Generated by Django 3.2 on 2021-04-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'trade_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('code', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='1C Code')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'trade_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сurrency Name')),
                ('code', models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'trade_сurrency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, verbose_name='Product Name')),
                ('code', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='1C Code')),
                ('vendor_code', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Vendor Code')),
                ('product_code', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Product Code')),
                ('bar_code', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Bar Code')),
                ('default_warranty', models.IntegerField(blank=True, default=None, null=True, verbose_name='Default Warranty')),
                ('default_price', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True, verbose_name='Default Price')),
                ('is_service', models.BooleanField(default=False, verbose_name='Service')),
                ('search_code', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Code for Search')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.brands')),
                ('categories', models.ManyToManyField(blank=True, to='Product.Categories')),
                ('currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.currencies')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'trade_products',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='currencies',
            constraint=models.UniqueConstraint(fields=('name',), name='u_trade_сur'),
        ),
        migrations.AddConstraint(
            model_name='currencies',
            constraint=models.UniqueConstraint(fields=('code',), name='u_trade_сur_code'),
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.categories'),
        ),
        migrations.AddConstraint(
            model_name='brands',
            constraint=models.UniqueConstraint(fields=('name',), name='u_trade_brand'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['vendor_code'], name='trade_produ_vendor__9b01d1_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['product_code'], name='trade_produ_product_f74620_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['bar_code'], name='trade_produ_bar_cod_4b172a_idx'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('code',), name='u_trade_prod_code'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='u_trade_prod_name'),
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='u_trade_cat'),
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(fields=('code',), name='u_trade_cat_code'),
        ),
    ]
