# Generated by Django 3.2 on 2021-04-07 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, verbose_name='Название')),
                ('full_name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Полное имя')),
                ('alt_name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Дополнительное имя')),
                ('code', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='1C Код')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Может быть покупателем')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Модет быть продавцом')),
                ('is_service', models.BooleanField(default=False, verbose_name='Может принимать в сервис')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Counterparty.partner')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'partner',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('name',), name='u_partner_name'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('code',), name='u_partner_code'),
        ),
    ]
